language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
matrix:
  allow_failures:
    - php: 5.5

before_install:
  - composer install --dev

script:
 - phpunit --log-junit /tmp/nb-phpunit-log.xml --configuration ./phpunit.xml ./src/Umbrella/Ya/Boleto/Tests
